package org.net9.redbud.storage.hibernate.userinfo;

import org.net9.redbud.storage.hibernate.login.Login;



/**
 * AbstractUserinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractUserinfo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private Short grade;
     private String gender;
     private String nation;
     private Short department;
     private String classnum;
     private String political;
     private String tel;
     private String mobile;
     private String email;
     private String address;
     private Short ability1;
     private Short ability2;
     private Short ability3;
     private Short ability4;
     private Short ability5;
     private Short ability6;
     private String postRec;
     private String trainingRec;
     private String activityRec;
     private String specialty;
     private Login login;


    // Constructors

    /** default constructor */
    public AbstractUserinfo() {
    }

	/** minimal constructor */
    public AbstractUserinfo(Integer id, String name, Short grade, String gender, String nation, Short department, String classnum, String political, String tel, String mobile, String email, String address, Short ability1, Short ability2, Short ability3, Short ability4, Short ability5, Short ability6, String specialty) {
        this.id = id;
        this.name = name;
        this.grade = grade;
        this.gender = gender;
        this.nation = nation;
        this.department = department;
        this.classnum = classnum;
        this.political = political;
        this.tel = tel;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.ability1 = ability1;
        this.ability2 = ability2;
        this.ability3 = ability3;
        this.ability4 = ability4;
        this.ability5 = ability5;
        this.ability6 = ability6;
        this.specialty = specialty;
    }
    
    /** full constructor */
    public AbstractUserinfo(Integer id, String name, Short grade, String gender, String nation, Short department, String classnum, String political, String tel, String mobile, String email, String address, Short ability1, Short ability2, Short ability3, Short ability4, Short ability5, Short ability6, String postRec, String trainingRec, String activityRec, String specialty) {
        this.id = id;
        this.name = name;
        this.grade = grade;
        this.gender = gender;
        this.nation = nation;
        this.department = department;
        this.classnum = classnum;
        this.political = political;
        this.tel = tel;
        this.mobile = mobile;
        this.email = email;
        this.address = address;
        this.ability1 = ability1;
        this.ability2 = ability2;
        this.ability3 = ability3;
        this.ability4 = ability4;
        this.ability5 = ability5;
        this.ability6 = ability6;
        this.postRec = postRec;
        this.trainingRec = trainingRec;
        this.activityRec = activityRec;
        this.specialty = specialty;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Short getGrade() {
        return this.grade;
    }
    
    public void setGrade(Short grade) {
        this.grade = grade;
    }

    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getNation() {
        return this.nation;
    }
    
    public void setNation(String nation) {
        this.nation = nation;
    }

    public Short getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Short department) {
        this.department = department;
    }

    public String getClassnum() {
        return this.classnum;
    }
    
    public void setClassnum(String classnum) {
        this.classnum = classnum;
    }

    public String getPolitical() {
        return this.political;
    }
    
    public void setPolitical(String political) {
        this.political = political;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public Short getAbility1() {
        return this.ability1;
    }
    
    public void setAbility1(Short ability1) {
        this.ability1 = ability1;
    }

    public Short getAbility2() {
        return this.ability2;
    }
    
    public void setAbility2(Short ability2) {
        this.ability2 = ability2;
    }

    public Short getAbility3() {
        return this.ability3;
    }
    
    public void setAbility3(Short ability3) {
        this.ability3 = ability3;
    }

    public Short getAbility4() {
        return this.ability4;
    }
    
    public void setAbility4(Short ability4) {
        this.ability4 = ability4;
    }

    public Short getAbility5() {
        return this.ability5;
    }
    
    public void setAbility5(Short ability5) {
        this.ability5 = ability5;
    }

    public Short getAbility6() {
        return this.ability6;
    }
    
    public void setAbility6(Short ability6) {
        this.ability6 = ability6;
    }

    public String getPostRec() {
        return this.postRec;
    }
    
    public void setPostRec(String postRec) {
        this.postRec = postRec;
    }

    public String getTrainingRec() {
        return this.trainingRec;
    }
    
    public void setTrainingRec(String trainingRec) {
        this.trainingRec = trainingRec;
    }

    public String getActivityRec() {
        return this.activityRec;
    }
    
    public void setActivityRec(String activityRec) {
        this.activityRec = activityRec;
    }

    public String getSpecialty() {
        return this.specialty;
    }
    
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

	public Login getLogin() {
		return login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}
   








}