package org.net9.redbud.storage.hibernate.login;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Login generated by MyEclipse - Hibernate Tools
 */
public class Login extends AbstractLogin implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 7327799255045858514L;

	/** default constructor */
    public Login() {
    }

	/** minimal constructor */
    public Login(Integer id, String studentnum, String password) {
        super(id, studentnum, password);        
    }
    
    /** full constructor */
    public Login(Integer id, String studentnum, String password, Set postses, Set posrecords) {
        super(id, studentnum, password, postses, posrecords);        
    }
   
}
