package org.net9.redbud.storage.hibernate.internaltasklogin;

import org.net9.redbud.storage.hibernate.internaltask.Internaltask;
import org.net9.redbud.storage.hibernate.login.Login;
// Generated by MyEclipse - Hibernate Tools



/**
 * Internaltasklogin generated by MyEclipse - Hibernate Tools
 */
public class Internaltasklogin extends AbstractInternaltasklogin implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 3620923710504733680L;


	/** default constructor */
    public Internaltasklogin() {
    }

    
    /** full constructor */
    public Internaltasklogin(Integer id, Internaltask internaltask, Login login, String readstatus, String echostatus) {
        super(id, internaltask, login, readstatus, echostatus);        
    }
   
}
