package org.net9.redbud.storage.hibernate.login;

import java.util.HashSet;
import java.util.Set;

import org.net9.redbud.storage.hibernate.userinfo.Userinfo;


/**
 * AbstractLogin generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractLogin  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String studentnum;
     private String password;
     private Userinfo userinfo;
     private Set postses = new HashSet(0);
     private Set posrecords = new HashSet(0);
     private Set publicinfologins = new HashSet(0);
     private Set internaltasklogins = new HashSet(0);
     private Set internalinfologins = new HashSet(0);

    // Constructors

    public Userinfo getUserinfo() {
		return userinfo;
	}

	public void setUserinfo(Userinfo userinfo) {
		this.userinfo = userinfo;
	}

	/** default constructor */
    public AbstractLogin() {
    }

	/** minimal constructor */
    public AbstractLogin(Integer id, String studentnum, String password) {
        this.id = id;
        this.studentnum = studentnum;
        this.password = password;
    }
    
    /** full constructor */
    public AbstractLogin(Integer id, String studentnum, String password, Set postses, Set posrecords) {
        this.id = id;
        this.studentnum = studentnum;
        this.password = password;
        this.postses = postses;
        this.posrecords = posrecords;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getStudentnum() {
        return this.studentnum;
    }
    
    public void setStudentnum(String studentnum) {
        this.studentnum = studentnum;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }

    public Set getPosrecords() {
        return this.posrecords;
    }
    
    public void setPosrecords(Set posrecords) {
        this.posrecords = posrecords;
    }

	public Set getPublicinfologins() {
		return publicinfologins;
	}

	public void setPublicinfologins(Set publicinfologins) {
		this.publicinfologins = publicinfologins;
	}

	public Set getInternalinfologins() {
		return internalinfologins;
	}

	public void setInternalinfologins(Set internalinfologins) {
		this.internalinfologins = internalinfologins;
	}

	public Set getInternaltasklogins() {
		return internaltasklogins;
	}

	public void setInternaltasklogins(Set internaltasklogins) {
		this.internaltasklogins = internaltasklogins;
	}
   








}