package org.net9.redbud.storage.hibernate.posts;

import org.net9.redbud.storage.hibernate.depts.Depts;
import org.net9.redbud.storage.hibernate.login.Login;



/**
 * AbstractPosts generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPosts  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Depts depts;
     private Login login;
     private String code;
     private String name;
     private String fullcode;
     private String fullname;
     private String description;
     private Short weight;
     private Float coefficient;
     private String categoryCode;
     private String organCode;
     private String deptCode;
     private String posReq;
     private Short posAbility1;
     private Short posAbility2;
     private Short posAbility3;
     private Short posAbility4;
     private Short posAbility5;
     private Short posAbility6;
     private String posCost;
     private String relatedPos;


    // Constructors

    /** default constructor */
    public AbstractPosts() {
    }

	/** minimal constructor */
    public AbstractPosts(Integer id, Depts depts, String code, String name, String fullcode, String fullname, String description, Short weight, Float coefficient, String categoryCode, String organCode, String deptCode, String posReq, Short posAbility1, Short posAbility2, Short posAbility3, Short posAbility4, Short posAbility5, Short posAbility6, String posCost, String relatedPos) {
        this.id = id;
        this.depts = depts;
        this.code = code;
        this.name = name;
        this.fullcode = fullcode;
        this.fullname = fullname;
        this.description = description;
        this.weight = weight;
        this.coefficient = coefficient;
        this.categoryCode = categoryCode;
        this.organCode = organCode;
        this.deptCode = deptCode;
        this.posReq = posReq;
        this.posAbility1 = posAbility1;
        this.posAbility2 = posAbility2;
        this.posAbility3 = posAbility3;
        this.posAbility4 = posAbility4;
        this.posAbility5 = posAbility5;
        this.posAbility6 = posAbility6;
        this.posCost = posCost;
        this.relatedPos = relatedPos;
    }
    
    /** full constructor */
    public AbstractPosts(Integer id, Depts depts, Login login, String code, String name, String fullcode, String fullname, String description, Short weight, Float coefficient, String categoryCode, String organCode, String deptCode, String posReq, Short posAbility1, Short posAbility2, Short posAbility3, Short posAbility4, Short posAbility5, Short posAbility6, String posCost, String relatedPos) {
        this.id = id;
        this.depts = depts;
        this.login = login;
        this.code = code;
        this.name = name;
        this.fullcode = fullcode;
        this.fullname = fullname;
        this.description = description;
        this.weight = weight;
        this.coefficient = coefficient;
        this.categoryCode = categoryCode;
        this.organCode = organCode;
        this.deptCode = deptCode;
        this.posReq = posReq;
        this.posAbility1 = posAbility1;
        this.posAbility2 = posAbility2;
        this.posAbility3 = posAbility3;
        this.posAbility4 = posAbility4;
        this.posAbility5 = posAbility5;
        this.posAbility6 = posAbility6;
        this.posCost = posCost;
        this.relatedPos = relatedPos;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Depts getDepts() {
        return this.depts;
    }
    
    public void setDepts(Depts depts) {
        this.depts = depts;
    }

    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getFullcode() {
        return this.fullcode;
    }
    
    public void setFullcode(String fullcode) {
        this.fullcode = fullcode;
    }

    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Short getWeight() {
        return this.weight;
    }
    
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    public Float getCoefficient() {
        return this.coefficient;
    }
    
    public void setCoefficient(Float coefficient) {
        this.coefficient = coefficient;
    }

    public String getCategoryCode() {
        return this.categoryCode;
    }
    
    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public String getOrganCode() {
        return this.organCode;
    }
    
    public void setOrganCode(String organCode) {
        this.organCode = organCode;
    }

    public String getDeptCode() {
        return this.deptCode;
    }
    
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    public String getPosReq() {
        return this.posReq;
    }
    
    public void setPosReq(String posReq) {
        this.posReq = posReq;
    }

    public Short getPosAbility1() {
        return this.posAbility1;
    }
    
    public void setPosAbility1(Short posAbility1) {
        this.posAbility1 = posAbility1;
    }

    public Short getPosAbility2() {
        return this.posAbility2;
    }
    
    public void setPosAbility2(Short posAbility2) {
        this.posAbility2 = posAbility2;
    }

    public Short getPosAbility3() {
        return this.posAbility3;
    }
    
    public void setPosAbility3(Short posAbility3) {
        this.posAbility3 = posAbility3;
    }

    public Short getPosAbility4() {
        return this.posAbility4;
    }
    
    public void setPosAbility4(Short posAbility4) {
        this.posAbility4 = posAbility4;
    }

    public Short getPosAbility5() {
        return this.posAbility5;
    }
    
    public void setPosAbility5(Short posAbility5) {
        this.posAbility5 = posAbility5;
    }

    public Short getPosAbility6() {
        return this.posAbility6;
    }
    
    public void setPosAbility6(Short posAbility6) {
        this.posAbility6 = posAbility6;
    }

    public String getPosCost() {
        return this.posCost;
    }
    
    public void setPosCost(String posCost) {
        this.posCost = posCost;
    }

    public String getRelatedPos() {
        return this.relatedPos;
    }
    
    public void setRelatedPos(String relatedPos) {
        this.relatedPos = relatedPos;
    }
   








}