package org.net9.redbud.storage.hibernate.posts;

import org.net9.redbud.storage.hibernate.depts.Depts;
// Generated by MyEclipse - Hibernate Tools
import org.net9.redbud.storage.hibernate.login.Login;

/**
 * Posts generated by MyEclipse - Hibernate Tools
 */
public class Posts extends AbstractPosts implements java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = -6743847483601972927L;

	/** default constructor */
	public Posts() {
	}

	/** minimal constructor */
	public Posts(Integer id, Depts depts, String code, String name,
			String fullcode, String fullname, String description, Short weight,
			Float coefficient, String categoryCode, String organCode,
			String deptCode, String posReq, Short posAbility1,
			Short posAbility2, Short posAbility3, Short posAbility4,
			Short posAbility5, Short posAbility6, String posCost,
			String relatedPos) {
		super(id, depts, code, name, fullcode, fullname, description, weight,
				coefficient, categoryCode, organCode, deptCode, posReq,
				posAbility1, posAbility2, posAbility3, posAbility4,
				posAbility5, posAbility6, posCost, relatedPos);
	}

	/** full constructor */
	public Posts(Integer id, Depts depts, Login login, String code,
			String name, String fullcode, String fullname, String description,
			Short weight, Float coefficient, String categoryCode,
			String organCode, String deptCode, String posReq,
			Short posAbility1, Short posAbility2, Short posAbility3,
			Short posAbility4, Short posAbility5, Short posAbility6,
			String posCost, String relatedPos) {
		super(id, depts, login, code, name, fullcode, fullname, description,
				weight, coefficient, categoryCode, organCode, deptCode, posReq,
				posAbility1, posAbility2, posAbility3, posAbility4,
				posAbility5, posAbility6, posCost, relatedPos);
	}

}
