package org.net9.redbud.storage.hibernate.organs;

import java.util.HashSet;
import java.util.Set;

import org.net9.redbud.storage.hibernate.category.Category;


/**
 * AbstractOrgans generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractOrgans  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Category category;
     private String code;
     private String name;
     private String description;
     private Set deptses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractOrgans() {
    }

	/** minimal constructor */
    public AbstractOrgans(Integer id, Category category, String code, String name, String description) {
        this.id = id;
        this.category = category;
        this.code = code;
        this.name = name;
        this.description = description;
    }
    
    /** full constructor */
    public AbstractOrgans(Integer id, Category category, String code, String name, String description, Set deptses) {
        this.id = id;
        this.category = category;
        this.code = code;
        this.name = name;
        this.description = description;
        this.deptses = deptses;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getDeptses() {
        return this.deptses;
    }
    
    public void setDeptses(Set deptses) {
        this.deptses = deptses;
    }
   








}