package org.net9.redbud.storage.hibernate.applytraining;



/**
 * AbstractApplytrainging generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractApplytrainging  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String studentnum;
     private Integer trainingid;
     private String applyreason;
     private String applystatus;
     private String applytime;
     private String trainingname;


    // Constructors

    /** default constructor */
    public AbstractApplytrainging() {
    }

	/** minimal constructor */
    public AbstractApplytrainging(Integer id, String studentnum, Integer trainingid, String applyreason, String applystatus, String applytime) {
        this.id = id;
        this.studentnum = studentnum;
        this.trainingid = trainingid;
        this.applyreason = applyreason;
        this.applystatus = applystatus;
        this.applytime = applytime;
    }
    
    /** full constructor */
    public AbstractApplytrainging(Integer id, String studentnum, Integer trainingid, String applyreason, String applystatus, String applytime, String trainingname) {
        this.id = id;
        this.studentnum = studentnum;
        this.trainingid = trainingid;
        this.applyreason = applyreason;
        this.applystatus = applystatus;
        this.applytime = applytime;
        this.trainingname = trainingname;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getStudentnum() {
        return this.studentnum;
    }
    
    public void setStudentnum(String studentnum) {
        this.studentnum = studentnum;
    }

    public Integer getTrainingid() {
        return this.trainingid;
    }
    
    public void setTrainingid(Integer trainingid) {
        this.trainingid = trainingid;
    }

    public String getApplyreason() {
        return this.applyreason;
    }
    
    public void setApplyreason(String applyreason) {
        this.applyreason = applyreason;
    }

    public String getApplystatus() {
        return this.applystatus;
    }
    
    public void setApplystatus(String applystatus) {
        this.applystatus = applystatus;
    }

    public String getApplytime() {
        return this.applytime;
    }
    
    public void setApplytime(String applytime) {
        this.applytime = applytime;
    }

    public String getTrainingname() {
        return this.trainingname;
    }
    
    public void setTrainingname(String trainingname) {
        this.trainingname = trainingname;
    }
   








}