package org.net9.redbud.storage.hibernate.applytraining;
// Generated by MyEclipse - Hibernate Tools



/**
 * Applytrainging generated by MyEclipse - Hibernate Tools
 */
public class Applytrainging extends AbstractApplytrainging implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 2681974080004350514L;

	/** default constructor */
    public Applytrainging() {
    }

	/** minimal constructor */
    public Applytrainging(Integer id, String studentnum, Integer trainingid, String applyreason, String applystatus, String applytime) {
        super(id, studentnum, trainingid, applyreason, applystatus, applytime);        
    }
    
    /** full constructor */
    public Applytrainging(Integer id, String studentnum, Integer trainingid, String applyreason, String applystatus, String applytime, String trainingname) {
        super(id, studentnum, trainingid, applyreason, applystatus, applytime, trainingname);        
    }
   
}
