package org.net9.redbud.storage.hibernate.training;



/**
 * AbstractTraining generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTraining  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String name;
     private String description;
     private String postcode;
     private String starttime;
     private String endtime;
     private Integer ispublic;
     private String deadline;
     private String posttime;
     private String validtime;
     private Integer istokened;
     private String filelist;


    // Constructors


	public String getValidtime() {
		return validtime;
	}

	public void setValidtime(String validtime) {
		this.validtime = validtime;
	}

	/** default constructor */
    public AbstractTraining() {
    }

	/** minimal constructor */
    public AbstractTraining(Integer id, String name, String description, String postcode, String starttime, String endtime, Integer ispublic, String posttime) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.postcode = postcode;
        this.starttime = starttime;
        this.endtime = endtime;
        this.ispublic = ispublic;
        this.posttime = posttime;
    }
    
    /** full constructor */
    public AbstractTraining(Integer id, String name, String description, String postcode, String starttime, String endtime, Integer ispublic, String deadline, String posttime) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.postcode = postcode;
        this.starttime = starttime;
        this.endtime = endtime;
        this.ispublic = ispublic;
        this.deadline = deadline;
        this.posttime = posttime;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getPostcode() {
        return this.postcode;
    }
    
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getStarttime() {
        return this.starttime;
    }
    
    public void setStarttime(String starttime) {
        this.starttime = starttime;
    }

    public String getEndtime() {
        return this.endtime;
    }
    
    public void setEndtime(String endtime) {
        this.endtime = endtime;
    }

    public Integer getIspublic() {
        return this.ispublic;
    }
    
    public void setIspublic(Integer ispublic) {
        this.ispublic = ispublic;
    }

    public String getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(String deadline) {
        this.deadline = deadline;
    }

    public String getPosttime() {
        return this.posttime;
    }
    
    public void setPosttime(String posttime) {
        this.posttime = posttime;
    }

	public Integer getIstokened() {
		return istokened;
	}

	public void setIstokened(Integer istokened) {
		this.istokened = istokened;
	}

	public String getFilelist() {
		return filelist;
	}

	public void setFilelist(String filelist) {
		this.filelist = filelist;
	}
   








}