package org.net9.redbud.storage.hibernate.internaltasklogin;

import org.net9.redbud.storage.hibernate.internaltask.Internaltask;
import org.net9.redbud.storage.hibernate.login.Login;



/**
 * AbstractInternaltasklogin generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractInternaltasklogin  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Internaltask internaltask;
     private Login login;
     private String readstatus;
     private String echostatus;


    // Constructors

    /** default constructor */
    public AbstractInternaltasklogin() {
    }

    
    /** full constructor */
    public AbstractInternaltasklogin(Integer id, Internaltask internaltask, Login login, String readstatus , String echostatus) {
        this.id = id;
        this.internaltask = internaltask;
        this.login = login;
        this.readstatus = readstatus;
        this.echostatus = echostatus;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Internaltask getInternaltask() {
        return this.internaltask;
    }
    
    public void setInternaltask(Internaltask internaltask) {
        this.internaltask = internaltask;
    }

    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }


	public String getEchostatus() {
		return echostatus;
	}


	public void setEchostatus(String echostatus) {
		this.echostatus = echostatus;
	}


	public String getReadstatus() {
		return readstatus;
	}


	public void setReadstatus(String readstatus) {
		this.readstatus = readstatus;
	}

}