package org.net9.redbud.storage.hibernate.category;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Category generated by MyEclipse - Hibernate Tools
 */
public class Category extends AbstractCategory implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -2923630429860799062L;

	/** default constructor */
    public Category() {
    }

	/** minimal constructor */
    public Category(Integer id, String code, String name) {
        super(id, code, name);        
    }
    
    /** full constructor */
    public Category(Integer id, String code, String name, String description, Set organses) {
        super(id, code, name, description, organses);        
    }
   
}
