package org.net9.redbud.storage.hibernate.publicinfologin;

import org.net9.redbud.storage.hibernate.login.Login;
import org.net9.redbud.storage.hibernate.publicinfo.Publicinfo;



/**
 * AbstractPublicinfologin generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPublicinfologin  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Login login;
     private Publicinfo publicinfo;
     private String status;


    // Constructors

    /** default constructor */
    public AbstractPublicinfologin() {
    }

    
    /** full constructor */
    public AbstractPublicinfologin(Integer id, Login login, Publicinfo publicinfo, String status) {
        this.id = id;
        this.login = login;
        this.publicinfo = publicinfo;
        this.status = status;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    public Publicinfo getPublicinfo() {
        return this.publicinfo;
    }
    
    public void setPublicinfo(Publicinfo publicinfo) {
        this.publicinfo = publicinfo;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}