package org.net9.redbud.storage.hibernate.depts;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;

import org.net9.redbud.storage.hibernate.organs.Organs;


/**
 * Depts generated by MyEclipse - Hibernate Tools
 */
public class Depts extends AbstractDepts implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 354357819249860957L;

	/** default constructor */
    public Depts() {
    }

	/** minimal constructor */
    public Depts(Integer id, Organs organs, String code, String name, String description) {
        super(id, organs, code, name, description);        
    }
    
    /** full constructor */
    public Depts(Integer id, Organs organs, String code, String name, String description, Set postses) {
        super(id, organs, code, name, description, postses);        
    }
   
}
