package org.net9.redbud.storage.hibernate.internalinfologin;

import org.net9.redbud.storage.hibernate.internalinfo.Internalinfo;
// Generated by MyEclipse - Hibernate Tools
import org.net9.redbud.storage.hibernate.login.Login;



/**
 * Internalinfologin generated by MyEclipse - Hibernate Tools
 */
public class Internalinfologin extends AbstractInternalinfologin implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -6667791953174896386L;


	/** default constructor */
    public Internalinfologin() {
    }

    
    /** full constructor */
    public Internalinfologin(Integer id, Internalinfo internalinfo, Login login, String status) {
        super();        
    }
   
}
