package org.net9.redbud.storage.hibernate.internaltask;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractInternaltask generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractInternaltask  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String tasktitle;
     private String taskcontent;
     private Long publishtime;
     private Integer ownerid;
     private String owenername;
     private String ownerposname;
     private String status;
     private Set internaltasklogins = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractInternaltask() {
    }

	/** minimal constructor */
    public AbstractInternaltask(Integer id, String tasktitle, String taskcontent, Long publishtime, Integer ownerid, String owenername, String ownerposname) {
        this.id = id;
        this.tasktitle = tasktitle;
        this.taskcontent = taskcontent;
        this.publishtime = publishtime;
        this.ownerid = ownerid;
        this.owenername = owenername;
        this.ownerposname = ownerposname;
    }
    
    /** full constructor */
    public AbstractInternaltask(Integer id, String tasktitle, String taskcontent, Long publishtime, Integer ownerid, String owenername, String ownerposname, Set internaltasklogins) {
        this.id = id;
        this.tasktitle = tasktitle;
        this.taskcontent = taskcontent;
        this.publishtime = publishtime;
        this.ownerid = ownerid;
        this.owenername = owenername;
        this.ownerposname = ownerposname;
        this.internaltasklogins = internaltasklogins;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTasktitle() {
        return this.tasktitle;
    }
    
    public void setTasktitle(String tasktitle) {
        this.tasktitle = tasktitle;
    }

    public String getTaskcontent() {
        return this.taskcontent;
    }
    
    public void setTaskcontent(String taskcontent) {
        this.taskcontent = taskcontent;
    }

    public Long getPublishtime() {
        return this.publishtime;
    }
    
    public void setPublishtime(Long publishtime) {
        this.publishtime = publishtime;
    }

    public Integer getOwnerid() {
        return this.ownerid;
    }
    
    public void setOwnerid(Integer ownerid) {
        this.ownerid = ownerid;
    }

    public String getOwenername() {
        return this.owenername;
    }
    
    public void setOwenername(String owenername) {
        this.owenername = owenername;
    }

    public String getOwnerposname() {
        return this.ownerposname;
    }
    
    public void setOwnerposname(String ownerposname) {
        this.ownerposname = ownerposname;
    }

    public Set getInternaltasklogins() {
        return this.internaltasklogins;
    }
    
    public void setInternaltasklogins(Set internaltasklogins) {
        this.internaltasklogins = internaltasklogins;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
   








}