package org.net9.redbud.storage.hibernate.internaltask;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Internaltask generated by MyEclipse - Hibernate Tools
 */
public class Internaltask extends AbstractInternaltask implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -3188470711497287491L;

	/** default constructor */
    public Internaltask() {
    }

	/** minimal constructor */
    public Internaltask(Integer id, String tasktitle, String taskcontent, Long publishtime, Integer ownerid, String owenername, String ownerposname) {
        super(id, tasktitle, taskcontent, publishtime, ownerid, owenername, ownerposname);        
    }
    
    /** full constructor */
    public Internaltask(Integer id, String tasktitle, String taskcontent, Long publishtime, Integer ownerid, String owenername, String ownerposname, Set internaltasklogins) {
        super(id, tasktitle, taskcontent, publishtime, ownerid, owenername, ownerposname, internaltasklogins);        
    }
   
}
