package org.net9.redbud.storage.hibernate.tokencontainer;
// Generated by MyEclipse - Hibernate Tools



/**
 * Tokencontainer generated by MyEclipse - Hibernate Tools
 */
public class Tokencontainer extends AbstractTokencontainer implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5120287670431740303L;


	// Constructors

    /** default constructor */
    public Tokencontainer() {
    }

    
    /** full constructor */
    public Tokencontainer(Integer id, String password, Integer objectid) {
        super(id, password, objectid);        
    }
   
}
