package org.net9.redbud.storage.hibernate.publicinfo;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * Publicinfo generated by MyEclipse - Hibernate Tools
 */
public class Publicinfo extends AbstractPublicinfo implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -6034114769634746054L;

	/** default constructor */
    public Publicinfo() {
    }

	/** minimal constructor */
    public Publicinfo(Integer id, String infotitle, String infocontent, Integer ownerid, String owenercatename, Long publishtime, Long approvetime, Integer approvestatus) {
        super(id, infotitle, infocontent, ownerid, owenercatename, publishtime, approvetime, approvestatus);        
    }
    
    /** full constructor */
    public Publicinfo(Integer id, String infotitle, String infocontent, Integer ownerid, String owenercatename, Long publishtime, Long approvetime, Integer approvestatus, Set publicinfologins) {
        super(id, infotitle, infocontent, ownerid, owenercatename, publishtime, approvetime, approvestatus, publicinfologins);        
    }
   
}
