package org.net9.redbud.storage.hibernate.publicinfologin;

import org.net9.redbud.storage.hibernate.login.Login;
// Generated by MyEclipse - Hibernate Tools
import org.net9.redbud.storage.hibernate.publicinfo.Publicinfo;



/**
 * Publicinfologin generated by MyEclipse - Hibernate Tools
 */
public class Publicinfologin extends AbstractPublicinfologin implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 4301534862168523301L;


	/** default constructor */
    public Publicinfologin() {
    }

    
    /** full constructor */
    public Publicinfologin(Integer id, Login login, Publicinfo publicinfo, String status) {
        super(id, login, publicinfo, status);        
    }
   
}
