package org.net9.redbud.storage.hibernate.internalinfo;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * Internalinfo generated by MyEclipse - Hibernate Tools
 */
public class Internalinfo extends AbstractInternalinfo implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -681626767417875308L;


	/** default constructor */
    public Internalinfo() {
    }

    
    /** full constructor */
    public Internalinfo(Integer id, String infotitle, String infocontent, Date publishtime, Integer ownerid, String ownername, String ownerpos) {
        super();        
    }
   
}
