package org.net9.redbud.storage.hibernate.apply;
// Generated by MyEclipse - Hibernate Tools



/**
 * Apply generated by MyEclipse - Hibernate Tools
 */
public class Apply extends AbstractApply implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = 7870790315223103262L;


	/** default constructor */
    public Apply() {
    }

    
    /** full constructor */
    public Apply(Integer id, String studentnum, String poscode, String applyreason, String poscategory, String applytime, String applystatus) {
        super(id, studentnum, poscode, applyreason, poscategory, applytime, applystatus);        
    }
   
}
