package org.net9.redbud.storage.hibernate.depts;

import java.util.HashSet;
import java.util.Set;

import org.net9.redbud.storage.hibernate.organs.Organs;


/**
 * AbstractDepts generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractDepts  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Organs organs;
     private String code;
     private String name;
     private String description;
     private Set postses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractDepts() {
    }

	/** minimal constructor */
    public AbstractDepts(Integer id, Organs organs, String code, String name, String description) {
        this.id = id;
        this.organs = organs;
        this.code = code;
        this.name = name;
        this.description = description;
    }
    
    /** full constructor */
    public AbstractDepts(Integer id, Organs organs, String code, String name, String description, Set postses) {
        this.id = id;
        this.organs = organs;
        this.code = code;
        this.name = name;
        this.description = description;
        this.postses = postses;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Organs getOrgans() {
        return this.organs;
    }
    
    public void setOrgans(Organs organs) {
        this.organs = organs;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Set getPostses() {
        return this.postses;
    }
    
    public void setPostses(Set postses) {
        this.postses = postses;
    }
   








}