package org.net9.redbud.storage.hibernate.internalinfologin;

import org.net9.redbud.storage.hibernate.internalinfo.Internalinfo;
import org.net9.redbud.storage.hibernate.login.Login;



/**
 * AbstractInternalinfologin generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractInternalinfologin  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Internalinfo internalinfo;
     private Login login;
     private String status;


    // Constructors

    /** default constructor */
    public AbstractInternalinfologin() {
    }

    
    /** full constructor */
    public AbstractInternalinfologin(Integer id, Internalinfo internalinfo, Login login, String status) {
        this.id = id;
        this.internalinfo = internalinfo;
        this.login = login;
        this.status = status;
    }

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Internalinfo getInternalinfo() {
        return this.internalinfo;
    }
    
    public void setInternalinfo(Internalinfo internalinfo) {
        this.internalinfo = internalinfo;
    }

    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
   








}